[common-etcd]
host = "127.0.0.1:2181"
basePath = "/gochat_srv"
serverPathLogic = "LogicRpc"
serverPathConnect = "ConnectRpc"
serverId = 1

[common-redis]
redisAddress = "127.0.0.1:6379"
redisPassword = ""
db = 0