[connect-base]
serverId = 1
certPath = ""
keyPath = ""

#[connect-test]
#    [[connect-test.item]]
#        name="lock"
#        age=18
#
#    [[connect-test.item]]
#        name="test"
#        age=20

[connect-websocket]
bind = "0.0.0.0:7000"


[connect-rpcLogicAddrs]
key = 1
addr = "tcp@0.0.0.0:6912"

[connect-bucket]
cpuNum = 4
channel = 1024
room = 1024
svrProto = 80
routineAmount = 32
routineSize = 20




